# Generated by Django 5.2.11 on 2026-02-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alteration', '0002_customer_tailor_remove_alteration_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alteration',
            old_name='item_description',
            new_name='issue_description',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='alteration',
            name='number_of_outfits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alterations', to='alteration.customer'),
        ),
        migrations.AlterField(
            model_name='alteration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
