# Generated by Django 5.2.11 on 2026-02-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='outfit_type',
            field=models.CharField(default='LHG', help_text='e.g. LHG', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
