# Generated by Django 5.2.11 on 2026-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_productsku_barcode_image_productsku_outfit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='sku_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
