# Generated by Django 5.2.11 on 2026-02-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outfittype'),
        ('sku', '0003_alter_productsku_sku_code'),
        ('supplier', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='supplier.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsku',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsku',
            name='outfit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.outfittype'),
        ),
    ]
