# Generated by Django 5.2.11 on 2026-02-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_sku',
        ),
    ]
