"""
Django settings for digital_boutique project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@h+u_el)9nn$-eybievpu!h5&r!-cmc1^(x$3rwe7dt!88)a24'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["192.168.29.31", "192.168.29.32"]
ALLOWED_HOSTS = ["192.168.29.31"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.location_field",
    "unfold.contrib.constance",
    "crispy_forms",
    "crispy_tailwind",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "core",
    "sku",
    "inventory",
    "supplier",
    "alteration",
    "forecasting",
    "api",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digital_boutique.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },  
    },
]

WSGI_APPLICATION = 'digital_boutique.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'laajavab_db',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '192.168.29.32',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#  unfold configuration
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Laajavab Boutique",
    "SITE_HEADER": "Laajavab Boutique",
    "SITE_DROPDOWN": [
        {"icon": "diamond", "title": _("My site"), "link": "/"},
    ],
    "SITE_URL": "/",
    "LOGIN": {"image": lambda request: static("core/img/lj_bot.png")},
    "SITE_ICON": lambda request: static("core/img/1.svg"),
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "BORDER_RADIUS": "10px",
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",
    "THEME": "light",
    "COLORS": {
        "base": {
            "50": "#FBF7F2",
            "100": "#F4ECE2",
            "200": "#E6D4C3",
            "300": "#D7BCA6",
            "400": "#C19A7B",
            "500": "#A8795D",
            "600": "#8C5736",
            "700": "#6E432A",
            "800": "#4F301D",
            "900": "#2E1C12",
        },
        "primary": {
            "50": "#FFF4F1",
            "100": "#FFE2DB",
            "200": "#FFC2B5",
            "300": "#FF9E8B",
            "400": "#F9735C",
            "500": "#EE9F8D",
            "600": "#8F4D3F",
            "700": "#68453D",
            "800": "#6E2414",
            "900": "#4F160D",
        },
        "font": {
            "subtle-light": "#8C5736",
            "subtle-dark": "#D7BCA6",
            "default-light": "#2E1C12",
            "default-dark": "#F4ECE2",
            "important-light": "#1A120B",
            "important-dark": "#FFFFFF",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {"en": "🇬🇧", "fr": "🇫🇷", "nl": "🇧🇪"},
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "command_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Suppliers"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Suppliers"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:supplier_supplier_changelist"),
                    },
                    {
                        "title": _("SecureOrderLinks"),
                        "icon": "link",
                        "link": reverse_lazy(
                            "admin:supplier_secureorderlink_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Inventory"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Discrepancies"),
                        "icon": "report_problem",
                        "link": reverse_lazy("admin:inventory_discrepancy_changelist"),
                    },
                    {
                        "title": _("Inventory Items"),
                        "icon": "inventory",
                        "link": reverse_lazy(
                            "admin:inventory_inventoryitem_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("SKU"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Product SKUs"),
                        "icon": "label",
                        "link": reverse_lazy("admin:sku_productsku_changelist"),
                    }
                ],
            },
            {
                "title": _("Alterations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tailors"),
                        "icon": "person",
                        "link": reverse_lazy("admin:alteration_tailor_changelist"),
                    },
                    {
                        "title": _("Customers"),
                        "icon": "group",
                        "link": reverse_lazy("admin:alteration_customer_changelist"),
                    },
                    {
                        "title": _("Alterations"),
                        "icon": "content_cut",
                        "link": reverse_lazy("admin:alteration_alteration_changelist"),
                    },
                ],
            },
            {
                "title": _("Clothing Categories"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:core_category_changelist"),
                    },
                    {
                        "title": _("Outfit Types"),
                        "icon": "checkroom",
                        "link": reverse_lazy("admin:core_outfittype_changelist"),
                    },
                ],
            },
        ],
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"
CRISPY_FAIL_SILENTLY = False
